version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "14:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "pip"
      prefix-development: "pip dev"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "14:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "GHA"
      include: "scope"
